// Package docsgen writes the generated half of docs/: the reference
// collection (CLI verbs, the adapter catalog, the canonical field registry,
// the ledger schema) and the glossary. Every page is a function of surfaces
// that already exist — `gtme help --agent`, docs/_adapters.json,
// spec/fields/*.json, spec/ledger.sql, and each concept page's `defines:` —
// so nothing here is hand-maintained. `make docs-reference` runs it, and
// the e2e suite fails when the committed pages drift from what it writes.
//
// Two shapes come out of every source (HANDOFF Track C, 2026-09-26): an
// index page a person reads, and one node per item that links and agents
// resolve to. Each generated file carries a `generated_by:` frontmatter key
// and a first-line YAML comment naming the generator.
package docsgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// GeneratedBy is the frontmatter value every generated page carries; Load
// and Write use it to tell generated files from authored ones.
const GeneratedBy = "make docs-reference (cmd/docsgen): gtme help --agent, docs/_adapters.json, spec/fields/*.json, spec/ledger.sql, and each concept page's defines:. Do not edit; fix the source and regenerate."

// markerLine is the first line inside every generated page's frontmatter.
const markerLine = "# generated by make docs-reference (cmd/docsgen); do not edit, fix the source and regenerate"

// generatedDirs are the docs/ paths the generator owns outright: a file
// under one of them that is not in the output is stale and removed.
var generatedDirs = []string{"reference/cli", "reference/adapters", "reference/fields", "reference/ledger-schema"}

// Inputs is everything Generate reads, already in memory so tests can feed
// fixtures and the e2e can feed the live binary's document.
type Inputs struct {
	Agent     []byte            // `gtme help --agent`, built-ins only
	Adapters  []byte            // docs/_adapters.json
	Fields    map[string][]byte // spec/fields/<type>.json by file name
	LedgerSQL string            // spec/ledger.sql
	Docs      map[string]string // authored pages by path under docs/ (never generated ones)
	Outline   string            // docs/_outline.yaml
}

// Output is what Generate writes: files by path under docs/, and the
// rewritten outline (reference children and the terms map).
type Output struct {
	Files   map[string]string
	Outline string
}

// Load reads Inputs from a repo checkout and the agent document at agentPath.
func Load(root, agentPath string) (Inputs, error) {
	var in Inputs
	var err error
	if in.Agent, err = os.ReadFile(agentPath); err != nil {
		return in, err
	}
	if in.Adapters, err = os.ReadFile(filepath.Join(root, "docs", "_adapters.json")); err != nil {
		return in, err
	}
	sql, err := os.ReadFile(filepath.Join(root, "spec", "ledger.sql"))
	if err != nil {
		return in, err
	}
	in.LedgerSQL = string(sql)
	in.Fields = map[string][]byte{}
	fieldFiles, _ := filepath.Glob(filepath.Join(root, "spec", "fields", "*.json"))
	for _, f := range fieldFiles {
		b, err := os.ReadFile(f)
		if err != nil {
			return in, err
		}
		in.Fields[filepath.Base(f)] = b
	}
	outline, err := os.ReadFile(filepath.Join(root, "docs", "_outline.yaml"))
	if err != nil {
		return in, err
	}
	in.Outline = string(outline)
	in.Docs = map[string]string{}
	docs := filepath.Join(root, "docs")
	err = filepath.WalkDir(docs, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		name := d.Name()
		if d.IsDir() {
			if strings.HasPrefix(name, "_") && path != docs {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(name, ".md") || strings.HasPrefix(name, "_") || name == "DESIGN.md" {
			return nil
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if IsGenerated(string(b)) {
			return nil
		}
		rel, _ := filepath.Rel(docs, path)
		in.Docs[filepath.ToSlash(rel)] = string(b)
		return nil
	})
	return in, err
}

// IsGenerated reports whether a page's frontmatter carries generated_by.
func IsGenerated(text string) bool {
	head := text
	if i := strings.Index(text[min(len(text), 3):], "\n---"); i >= 0 {
		head = text[:i+3]
	}
	return strings.Contains(head, "\ngenerated_by:")
}

// Write puts an Output on disk under docsDir and removes stale generated
// files from the directories the generator owns. It returns the paths it
// wrote or removed, sorted.
func Write(docsDir string, out *Output) ([]string, error) {
	var changed []string
	for _, dir := range generatedDirs {
		entries, _ := filepath.Glob(filepath.Join(docsDir, filepath.FromSlash(dir), "*.md"))
		for _, e := range entries {
			rel, _ := filepath.Rel(docsDir, e)
			rel = filepath.ToSlash(rel)
			if _, keep := out.Files[rel]; keep {
				continue
			}
			b, err := os.ReadFile(e)
			if err != nil || !IsGenerated(string(b)) {
				continue
			}
			if err := os.Remove(e); err != nil {
				return nil, err
			}
			changed = append(changed, "removed "+rel)
		}
	}
	for rel, content := range out.Files {
		path := filepath.Join(docsDir, filepath.FromSlash(rel))
		if cur, err := os.ReadFile(path); err == nil && string(cur) == content {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return nil, err
		}
		changed = append(changed, "wrote "+rel)
	}
	outlinePath := filepath.Join(docsDir, "_outline.yaml")
	if cur, err := os.ReadFile(outlinePath); err != nil || string(cur) != out.Outline {
		if err := os.WriteFile(outlinePath, []byte(out.Outline), 0o644); err != nil {
			return nil, err
		}
		changed = append(changed, "wrote _outline.yaml")
	}
	sort.Strings(changed)
	return changed, nil
}

// Drift compares an Output with what is on disk and returns the paths that
// differ (missing, stale, or changed), sorted; empty means in sync.
func Drift(docsDir string, out *Output) ([]string, error) {
	var drift []string
	for rel, content := range out.Files {
		cur, err := os.ReadFile(filepath.Join(docsDir, filepath.FromSlash(rel)))
		if err != nil {
			drift = append(drift, "missing "+rel)
		} else if string(cur) != content {
			drift = append(drift, "changed "+rel)
		}
	}
	for _, dir := range generatedDirs {
		entries, _ := filepath.Glob(filepath.Join(docsDir, filepath.FromSlash(dir), "*.md"))
		for _, e := range entries {
			rel, _ := filepath.Rel(docsDir, e)
			rel = filepath.ToSlash(rel)
			if _, keep := out.Files[rel]; keep {
				continue
			}
			if b, err := os.ReadFile(e); err == nil && IsGenerated(string(b)) {
				drift = append(drift, "stale "+rel)
			}
		}
	}
	if cur, err := os.ReadFile(filepath.Join(docsDir, "_outline.yaml")); err != nil || string(cur) != out.Outline {
		drift = append(drift, "changed _outline.yaml")
	}
	sort.Strings(drift)
	return drift, nil
}

// Generate renders every generated page and the outline from Inputs.
func Generate(in Inputs) (*Output, error) {
	agent, err := parseAgent(in.Agent)
	if err != nil {
		return nil, fmt.Errorf("help --agent: %w", err)
	}
	manifests, err := parseAdapters(in.Adapters)
	if err != nil {
		return nil, fmt.Errorf("docs/_adapters.json: %w", err)
	}
	types, err := parseFieldFiles(in.Fields)
	if err != nil {
		return nil, fmt.Errorf("spec/fields: %w", err)
	}
	objects, err := parseLedgerSQL(in.LedgerSQL)
	if err != nil {
		return nil, fmt.Errorf("spec/ledger.sql: %w", err)
	}
	pages, err := parseDocs(in.Docs)
	if err != nil {
		return nil, err
	}
	glossary, err := collectGlossary(pages)
	if err != nil {
		return nil, err
	}
	ctx := &site{agent: agent, adapters: manifests, types: types, objects: objects, pages: pages, glossary: glossary, backlinks: backlinks(pages)}

	var out []*page
	out = append(out, ctx.cliPages()...)
	out = append(out, ctx.adapterPages()...)
	out = append(out, ctx.fieldPages()...)
	out = append(out, ctx.ledgerPages()...)
	out = append(out, ctx.glossaryPage())

	files := map[string]string{}
	for _, p := range out {
		files[p.path] = ctx.assemble(p)
	}
	outline, err := rewriteOutline(in.Outline, ctx)
	if err != nil {
		return nil, err
	}
	return &Output{Files: files, Outline: outline}, nil
}

// site is the parsed inputs plus the derived indexes the renderers share.
type site struct {
	agent     *agentDoc
	adapters  []manifest
	types     []fieldType
	objects   []ledgerObject
	pages     []*docPage
	glossary  []entry
	backlinks map[string][]backlink
}

// page is one generated page before its frontmatter is assembled.
type page struct {
	path        string // under docs/, e.g. reference/cli/plan.md
	node        string // e.g. /reference/cli/plan
	name        string
	description string
	audience    string // frontmatter `for`
	learn       []string
	roles       []string
	extra       string // extra frontmatter lines, already indented YAML
	body        string // markdown after the frontmatter, starting with the h1
}

// assemble writes a page's frontmatter — including a see-also link to every
// concept page whose glossary terms the body mentions — and appends the body.
func (s *site) assemble(p *page) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString(markerLine + "\n")
	fmt.Fprintf(&b, "name: %s\n", yq(p.name))
	fmt.Fprintf(&b, "description: %s\n", yq(p.description))
	fmt.Fprintf(&b, "for: %s\n", yq(p.audience))
	b.WriteString("learn:\n")
	for _, l := range p.learn {
		fmt.Fprintf(&b, "  - %s\n", yq(l))
	}
	fmt.Fprintf(&b, "roles: [%s]\n", strings.Join(p.roles, ", "))
	fmt.Fprintf(&b, "generated_by: %s\n", yq(GeneratedBy))
	if p.extra != "" {
		b.WriteString(p.extra)
	}
	links := s.seeAlso(p)
	if len(links) > 0 {
		b.WriteString("links:\n")
		for _, l := range links {
			fmt.Fprintf(&b, "  - to: %s\n    type: relates-to\n    description: %s\n", l.to, yq(l.description))
		}
	}
	b.WriteString("---\n\n")
	b.WriteString(strings.TrimRight(p.body, "\n") + "\n")
	return b.String()
}

type link struct{ to, description string }

// seeAlso derives a page's related links from the glossary: one link per
// concept page whose terms the page's prose mentions, describing which
// terms. The lint's "mentioned but not linked" check reads the same map.
func (s *site) seeAlso(p *page) []link {
	prose := stripFences(p.body)
	byPage := map[string][]string{}
	for _, e := range s.glossary {
		if e.page == p.node {
			continue
		}
		if termRe(e.term).MatchString(prose) {
			byPage[e.page] = append(byPage[e.page], e.term)
		}
	}
	var out []link
	for pg, terms := range byPage {
		sort.Strings(terms)
		out = append(out, link{to: pg, description: "Defines " + joinAnd(terms)})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].to < out[j].to })
	return out
}

var termRes = map[string]*regexp.Regexp{}

func termRe(term string) *regexp.Regexp {
	if re, ok := termRes[term]; ok {
		return re
	}
	re := regexp.MustCompile(`(?i)\b` + regexp.QuoteMeta(term) + `(?:s|es)?\b`)
	termRes[term] = re
	return re
}

var fenceRe = regexp.MustCompile("(?s)```.*?```")

func stripFences(s string) string { return fenceRe.ReplaceAllString(s, "") }

// yq double-quotes a YAML scalar.
func yq(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", " ")
	return `"` + s + `"`
}

// cell escapes text for a markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.TrimSpace(s)
}

// prose escapes a source string for markdown prose: angle brackets would
// otherwise read as HTML and vanish on the site.
func prose(s string) string {
	s = strings.ReplaceAll(s, "<", `\<`)
	s = strings.ReplaceAll(s, ">", `\>`)
	return s
}

// code wraps text in backticks, choosing a fence long enough for its content.
func code(s string) string {
	if strings.Contains(s, "`") {
		return "`` " + s + " ``"
	}
	return "`" + s + "`"
}

func joinAnd(items []string) string {
	switch len(items) {
	case 0:
		return ""
	case 1:
		return items[0]
	case 2:
		return items[0] + " and " + items[1]
	}
	return strings.Join(items[:len(items)-1], ", ") + ", and " + items[len(items)-1]
}

// capitalize upper-cases the first letter of a sentence fragment, unless
// the first word is an identifier (a table, a flag, a path, `gtme`) whose
// case is part of its name.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	first := strings.Fields(s)[0]
	if first == "gtme" || strings.ContainsAny(first, "_/.-:") || strings.HasPrefix(first, "`") {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// sentence makes a full sentence from a `does` fragment.
func sentence(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return s
	}
	if !strings.HasSuffix(s, ".") && !strings.HasSuffix(s, ")") {
		s += "."
	}
	return capitalize(s)
}

// short trims a `does` string to one clause under 160 characters for a
// page description: cut at the first strong separator, then drop trailing
// clauses at commas until it fits, closing any parenthesis it opened.
func short(does string) string {
	s := does
	for _, sep := range []string{"; ", " — ", ": ", ". "} {
		if i := strings.Index(s, sep); i > 0 {
			s = s[:i]
		}
	}
	for len(s) > 160 {
		i := strings.LastIndex(s, ", ")
		if i <= 0 {
			s = s[:157] + "..."
			break
		}
		s = s[:i]
	}
	if strings.Count(s, "(") > strings.Count(s, ")") {
		s = strings.TrimSpace(s[:strings.LastIndex(s, "(")])
	}
	return capitalize(strings.TrimRight(strings.TrimSpace(s), ",."))
}

// table renders a markdown table; cells are escaped by the caller.
func table(header []string, rows [][]string) string {
	var b strings.Builder
	b.WriteString("| " + strings.Join(header, " | ") + " |\n")
	b.WriteString("|" + strings.Repeat("---|", len(header)) + "\n")
	for _, r := range rows {
		b.WriteString("| " + strings.Join(r, " | ") + " |\n")
	}
	return b.String()
}

func slugOf(id string) string { return strings.ReplaceAll(id, "/", "-") }
