package docsgen

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// glossaryPage renders docs/glossary.md: every `defines:` entry across the
// concept pages, alphabetical, each linking the page that owns it. The
// entries are also frontmatter data (`entries:`) for the site's hover cards.
func (s *site) glossaryPage() *page {
	var b strings.Builder
	b.WriteString("# Glossary\n\n")
	fmt.Fprintf(&b, "The %d words the docs use with one fixed meaning, one sentence each. Every entry links the concept page that defines it, and that page is where the meaning is explained with an example.\n\n", len(s.glossary))
	var rows [][]string
	for _, e := range s.glossary {
		rows = append(rows, []string{cell(e.term), cell(e.definition), fmt.Sprintf("[%s](%s)", e.pageName, e.page)})
	}
	b.WriteString(table([]string{"Term", "Means", "Defined on"}, rows))

	var extra strings.Builder
	extra.WriteString("entries:\n")
	for _, e := range s.glossary {
		fmt.Fprintf(&extra, "  - term: %s\n    definition: %s\n    page: %s\n", yq(e.term), yq(e.definition), e.page)
	}
	return &page{
		path:        "glossary.md",
		node:        "/glossary",
		name:        "Glossary",
		description: "Every project term in one sentence, alphabetical, each linking the concept page that defines it; generated from the pages' defines lists",
		audience:    "You met a word in the docs that carries a fixed meaning here and want that meaning and the page that explains it.",
		learn:       []string{"what each project term means, in one sentence", "which page owns each term"},
		roles:       []string{"operator", "builder", "extender", "agent"},
		extra:       extra.String(),
		body:        b.String(),
	}
}

// ---------------------------------------------------------------------------
// _outline.yaml: the generator owns the reference children and the terms map.

var termsBlockRe = regexp.MustCompile(`(?ms)^terms:.*\z`)

func rewriteOutline(outline string, s *site) (string, error) {
	if !strings.Contains(outline, "slug: glossary") {
		return "", fmt.Errorf("_outline.yaml: add `/glossary` under `pages:` so links to it resolve")
	}
	children := map[string][]string{}
	for _, v := range groupVerbs(s.agent.Verbs) {
		children["cli"] = append(children["cli"], v.Name)
	}
	for _, m := range s.adapters {
		children["adapters"] = append(children["adapters"], slugOf(m.ID))
	}
	for _, t := range s.types {
		children["fields"] = append(children["fields"], t.EntityType)
	}
	for _, o := range s.objects {
		children["ledger-schema"] = append(children["ledger-schema"], o.Name)
	}
	start := strings.Index(outline, "\n  reference:\n")
	if start < 0 {
		return "", fmt.Errorf("_outline.yaml: no reference collection")
	}
	head, tail := outline[:start], outline[start:]
	for slug, kids := range children {
		re := regexp.MustCompile(`(?m)^(\s*- \{ slug: ` + regexp.QuoteMeta(slug) + `, [^}]*?)(?:, children: \[([^\]]*)\])?( \})$`)
		m := re.FindStringSubmatch(tail)
		if m == nil {
			return "", fmt.Errorf("_outline.yaml: no reference entry for %s", slug)
		}
		// Keep any hand-listed child the generator does not produce (a planned page).
		have := map[string]bool{}
		for _, k := range kids {
			have[k] = true
		}
		for _, k := range strings.Split(m[2], ",") {
			k = strings.TrimSpace(k)
			if k != "" && !have[k] {
				kids = append(kids, k)
			}
		}
		tail = re.ReplaceAllString(tail, "${1}, children: ["+strings.Join(kids, ", ")+"]${3}")
	}
	outline = head + tail

	var terms strings.Builder
	terms.WriteString("terms:\n")
	terms.WriteString("  # Generated by make docs-reference from each concept page's defines:; do not hand-edit.\n")
	sorted := append([]entry{}, s.glossary...)
	sort.Slice(sorted, func(i, j int) bool { return strings.ToLower(sorted[i].term) < strings.ToLower(sorted[j].term) })
	for _, e := range sorted {
		fmt.Fprintf(&terms, "  %s: %s\n", strings.ToLower(e.term), e.page)
	}
	if !termsBlockRe.MatchString(outline) {
		return "", fmt.Errorf("_outline.yaml: no terms: block to rewrite")
	}
	return termsBlockRe.ReplaceAllLiteralString(outline, terms.String()), nil
}
